### ISSUE TITLE
Fix notices - static method calls

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-Social-Plugin#4]
Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method UCF_Social_Common::add_css() should not be called statically

Strict Standards: Non-static method UCF_Social_Common::ucf_social_icons_display_before() should not be called statically in UCF-Social-Plugin/includes/ucf-social-common.php on line 17

Strict Standards: Non-static method UCF_Social_Common::ucf_social_icons_display() should not be called statically in UCF-Social-Plugin/includes/ucf-social-common.php on line 22

Strict Standards: Non-static method UCF_Social_Common::ucf_social_icons_display_after() should not be called statically in UCF-Social-Plugin/includes/ucf-social-common.php on line 27

**Comment by rjucf** [comment]
Fixed with commit: https://github.com/UCF/UCF-Social-Plugin/commit/2466193057de4170d4787ceca106a4ec271ab9d8
